import numpy as np

'''
Generated by gemini prompt:
    I have a hiking app, and I am trying to establish the hiker's current bearing from the breadcrumbs (which are tracing the hiker's path). A simple approach would be to take the current breadcrumb and the previous one and to work out the bearing from the previous to the current. However, over rough terrain, the hiker would make many short adjustments to their path, which would mean that the bearing would move in many directions over a short period of time. I would like to provide general guidance to the hiker to maintain a course, but using only the present and previous breadcrumbs would lead to the app providing many course correction recommendations. How do you think the app could be modified to provide more useful course correction advice?
'''
def compute_bearing(p1, p2):
    """Compute bearing from p1 to p2 in degrees [0, 360)."""
    dx = p2[0] - p1[0]
    dy = p2[1] - p1[1]
    rad = np.arctan2(dy, dx)
    deg = np.degrees(rad)
    return (deg + 360) % 360

def angular_diff(a, b):
    """Compute shortest angular difference between two angles in degrees, handling wrap-around."""
    diff = (b - a + 180) % 360 - 180
    return np.abs(diff)

def generate_test_track():
    """Generates a synthetic true trail and a noisy GPS track."""
    np.random.seed(42)
    n_points = 120
    t = np.linspace(0, 8 * np.pi, n_points)
    
    # True trail path (winding with curves)
    true_x = t * 2.0
    true_y = np.sin(t / 2.0) * 25.0 + t * 0.8
    true_points = list(zip(true_x, true_y))
    
    # Add Gaussian GPS noise (jitter) simulating rough terrain / canopy
    noise_x = np.random.normal(0, 2.0, n_points)
    noise_y = np.random.normal(0, 2.0, n_points)
    gps_x = true_x + noise_x
    gps_y = true_y + noise_y
    gps_points = list(zip(gps_x, gps_y))
    
    # Calculate true headings for ground truth comparison
    true_bearings = [compute_bearing(true_points[i], true_points[i+1]) for i in range(len(true_points)-1)]
    
    return gps_points, true_points, true_bearings

# --- Method 1: Baseline (Immediate Previous Point) ---
def evaluate_baseline(points):
    bearings = []
    for i in range(1, len(points)):
        bearings.append(compute_bearing(points[i-1], points[i]))
    return bearings

# --- Method 2: Distance Lookback Window ---
def evaluate_distance_lookback(points, target_distance=15.0):
    bearings = []
    for i in range(len(points)):
        current = points[i]
        lookback_pt = points[0]
        # Look backward along breadcrumbs until distance threshold is met
        for j in range(i - 1, -1, -1):
            dist = np.hypot(current[0] - points[j][0], current[1] - points[j][1])
            if dist >= target_distance:
                lookback_pt = points[j]
                break
        bearings.append(compute_bearing(lookback_pt, current))
    return bearings[1:] # Align indices

# --- Method 3: Vector Exponential Moving Average (EMA) ---
def evaluate_vector_ema(points, alpha=0.3):
    bearings = []
    vec_x, vec_y = 0.0, 0.0
    for i in range(1, len(points)):
        dx = points[i][0] - points[i-1][0]
        dy = points[i][1] - points[i-1][1]
        mag = np.hypot(dx, dy)
        if mag > 0:
            ux, uy = dx / mag, dy / mag
            if i == 1:
                vec_x, vec_y = ux, uy
            else:
                vec_x = alpha * ux + (1 - alpha) * vec_x
                vec_y = alpha * uy + (1 - alpha) * vec_y
            smoothed_deg = (np.degrees(np.arctan2(vec_y, vec_x)) + 360) % 360
            bearings.append(smoothed_deg)
        else:
            bearings.append(bearings[-1] if bearings else 0.0)
    return bearings

# --- Run Simulation & Comparison ---
gps_points, true_points, true_bearings = generate_test_track()

b_baseline = evaluate_baseline(gps_points)
b_lookback = evaluate_distance_lookback(gps_points, target_distance=15.0)
b_ema = evaluate_vector_ema(gps_points, alpha=0.25)

# Metrics calculation function
def compute_metrics(calculated_bearings, true_bearings):
    # Trim to match lengths
    cb = calculated_bearings[-len(true_bearings):]
    tb = true_bearings[-len(cb):]
    
    # 1. Heading Jitter (Mean consecutive angular change)
    jumps = [angular_diff(cb[i], cb[i-1]) for i in range(1, len(cb))]
    mean_jitter = np.mean(jumps)
    
    # 2. Tracking Error (Mean absolute error vs ground truth true trail)
    errors = [angular_diff(cb[i], tb[i]) for i in range(len(cb))]
    mean_error = np.mean(errors)
    
    return mean_jitter, mean_error

jitter_base, err_base = compute_metrics(b_baseline, true_bearings)
jitter_look, err_look = compute_metrics(b_lookback, true_bearings)
jitter_ema, err_ema = compute_metrics(b_ema, true_bearings)

print("Algorithm Performance Comparison:")
print(f"{'Method':<25} | {'Heading Jitter (Lower=Smoother)':<30} | {'True Heading Error':<20}")
print("-" * 83)
print(f"{'Raw Baseline':<25} | {jitter_base:<30.2f}° | {err_base:<20.2f}°")
print(f"{'Distance Lookback (15m)':<25} | {jitter_look:<30.2f}° | {err_look:<20.2f}°")
print(f"{'Vector EMA (alpha=0.25)':<25} | {jitter_ema:<30.2f}° | {err_ema:<20.2f}°")
